<div id="content">
    <div class="container">

    </div>
</div>
<div class="wrapper" id="content-below">
    <div class="container">
        <div class="clients block">
            <h3 class="block-title">
                <span>Clients</span>
            </h3>
            <!--Recommended image sizing: 170px & 70px-->
            <ul class="thumbnails list-unstyled row">
                <li class="col-sm-2">
                    <a title="" data-original-title="HTML 5" data-placement="top" class="_tooltip" href="#">
                        <img alt="HTML 5" class="img-rounded" src="/uploads/clients/1.jpg">
                    </a>
                </li>
                <li class="col-sm-2">
                    <a title="" data-original-title="CSS 3" data-placement="top" class="_tooltip" href="#">
                        <img alt="CSS 3" class="img-rounded" src="/uploads/clients/2.jpg">
                    </a>
                </li>
                <li class="col-sm-2">
                    <a title="" data-original-title="Git Hub" data-placement="top" class="_tooltip" href="#">
                        <img alt="Git Hub" class="img-rounded" src="/uploads/clients/3.jpg">
                    </a>
                </li>
                <li class="col-sm-2">
                    <a title="" data-original-title="Amazon" data-placement="top" class="_tooltip" href="#">
                        <img alt="Amazon" class="img-rounded" src="/uploads/clients/4.jpg">
                    </a>
                </li>
                <li class="col-sm-2">
                    <a title="" data-original-title="Android" data-placement="top" class="_tooltip" href="#">
                        <img alt="Android" class="img-rounded" src="/uploads/clients/5.jpg">
                    </a>
                </li>
                <li class="col-sm-2">
                    <a title="" data-original-title="BBC" data-placement="top" class="_tooltip" href="#">
                        <img alt="BBC" class="img-rounded" src="/uploads/clients/6.jpg">
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
