<?php
    $this->headTitle('Services');
?>

<div id="highlighted">
    <div class="container">
        <div class="header">
            <h2 class="page-title">
                <span>Services</span> 
                <small>The services we offer &amp; how we can help you!</small>
            </h2>
        </div>
    </div>
</div>
<div id="content">
    <div class="container">
        
        <!-- Services -->        
        <div class="block services">
            <ul class="thumbnails row">

                <?php
                    $i = 0;
                    foreach ($this->services as $service) {
                        if($i % 4 === 0) { // kraj reda i prelazak u novi ?>  
                                </ul>
                            </div>
        
                            <div class="block services">
                                <ul class="thumbnails row">
                        <?php }
                        $i++;
//                        $memberUrl = $this->baseUrl('/aboutus/member/id/' . $member['id']);
//                        $memberImgUrl = $this->memberImgUrl($member);
                        ?>
                        <li class="col-md-3">
                            <h3 class="title">
                                <i class=" <?php echo $this->escape($service['icon']); ?> "></i> <?php echo $this->escape($service['title']); ?>
                            </h3>
                            <p> <?php echo $this->escape($service['description']); ?> </p>
                        </li>              
                <?php } ?>
                
            </ul>
        </div>
        
    </div>
</div>